baseurl: "https://raskell-io.github.io"
languageCode: "en-us"
title: "Raskell"
paginate: 6

params:
  titleLogo: favicon.ico
  
  siteName: "Raskell"
  siteDesc: "This is Raffael's own web space where he writes about tech, open-source and his life as a developer."
  author: "Raffael"

  colorScheme:
    toggle: true
    default: auto

  maxCategoryToShow: 10
  enableFootnotes: true

  socialOptions:
    dev-to:
    email:
    facebook:
    github:
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:
  
  comments:
    enabled: false

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
