baseurl: "https://raskell-io.github.io"
languageCode: "en-us"
title: "Raskell"
paginate: 6

params:
  titleLogo: favicon.ico
  
  siteName: "Raskell | Tech web space curated by Raffael Schneider"
  siteDesc: "This is Raffael's own web space where he writes about tech, open-source and his life as a software engineer. I write down whatever background noise my mind is producing so I can focus more when I need to."
  author: "Raffael"

  colorScheme:
    toggle: true
    default: auto

  maxCategoryToShow: 10
  enableFootnotes: true

  socialOptions:
    dev-to:
    email:
    facebook:
    github: https://github.com/raffaelschneider
    instagram:
    linkedin: https://ch.linkedin.com/in/raffael-e-schneider
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter: https://twitter.com/raskelll
    twitch:
    whatsapp:
  
  comments:
    enabled: false

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
